openapi: 3.1.0
info:
  title: Notes Domain API
  version: 1.0.0
  description: Notes Management
paths:
  /v1/notes:
    $ref: './components/paths/notes_list.yaml'
  /v1/notes/{id}:
    $ref: './components/paths/notes_detail.yaml'
components:
  schemas:
    Note:
      $ref: './components/schemas/Note.yaml'
