openapi: 3.1.0
info:
  title: Library Domain API
  version: 1.0.0
  description: File Library and Synchronization
paths:
  /v1/sync:
    $ref: './components/paths/sync.yaml'
  /v1/files:
    $ref: './components/paths/files_list.yaml'
components:
  schemas:
    File:
      $ref: './components/schemas/File.yaml'
    SyncPayload:
      $ref: './components/schemas/SyncPayload.yaml'
