services:
  xeocontext:
    # Prod option, best performance
    # image: xeost/xeocontext:latest
    # Dev option, with live-reload
    image: xeost/xeocontext-live-reload:latest
    container_name: xeodocs_system_design
    ports:
      - "12120:3000"
    volumes:
      - ./:/app/content
    restart: unless-stopped
