openapi: 3.1.0
info:
  title: Todos Domain API
  version: 1.0.0
  description: Todo Management
paths:
  /v1/todos:
    $ref: './components/paths/todos_list.yaml'
  /v1/todos/{id}:
    $ref: './components/paths/todos_detail.yaml'
components:
  schemas:
    Todo:
      $ref: './components/schemas/Todo.yaml'
